version: "3.8"

services:
  demo_api:
    container_name: demo_api
    build: .
    env_file:
      - .env
    working_dir: /app
    ports:
      - 3333:3333
    volumes:
      - .:/app
    depends_on:
      - demo_db
  demo_db:
    container_name: demo_mariadb
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./mariadb/initdb/:/docker-entrypoint-initdb.d/
      - ./mariadb/data/:/var/lib/mysql/
    ports:
      - "33061:3306"
